version: '{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
- ps: Install-Product node $env:node_version $env:node_arch
environment:
  FCOPY_GITHUB_TOKEN:
    secure: n0CaoaKAbHbWwXfY92ys9Ps22AGYOQae4kurS3UfHeEtB3lPUOXGpU900cVb0mh9
  FCOPY_REBUILD: 1
  FCOPY_NOFALLBACK: 1
  matrix:
  - node_version: 8.0.0
    node_arch: x64
  - node_version: 8.0.0
    node_arch: x86
  - node_version: 7.10.0
    node_arch: x64
  - node_version: 7.10.0
    node_arch: x86
  - node_version: 6.10.3
    node_arch: x64
  - node_version: 6.10.3
    node_arch: x86
test: off
deploy: off
build_script:
- cmd: >-
    npm install

    npm run test

    node -r babel-register ./scripts/publish-github-current.js